const countries = [
  { id: 4, globe_name: "Afghanistan", api_name: "Afghanistan" },
  { id: 8, globe_name: "Albania", api_name: "Albania" },
  { id: 12, globe_name: "Algeria", api_name: "Algeria" },
  { id: 24, globe_name: "Angola", api_name: "Angola" },
  { id: 10, globe_name: "Antarctica", api_name: null },
  { id: 32, globe_name: "Argentina", api_name: "Argentina" },
  { id: 51, globe_name: "Armenia", api_name: "Armenia" },
  { id: 36, globe_name: "Australia", api_name: "Australia" },
  { id: 40, globe_name: "Austria", api_name: "Austria" },
  { id: 31, globe_name: "Azerbaijan", api_name: "Azerbaijan" },
  { id: 44, globe_name: "Bahamas", api_name: "The Bahamas" },
  { id: 50, globe_name: "Bangladesh", api_name: "Bangladesh" },
  { id: 112, globe_name: "Belarus", api_name: "Belarus" },
  { id: 56, globe_name: "Belgium", api_name: "Belgium" },
  { id: 84, globe_name: "Belize", api_name: "Belize" },
  { id: 204, globe_name: "Benin", api_name: "Benin" },
  { id: 64, globe_name: "Bhutan", api_name: "Bhutan" },
  { id: 68, globe_name: "Bolivia, Plurinational State of", api_name: "Bolivia" },
  { id: 70, globe_name: "Bosnia and Herzegovina", api_name: "Bosnia and Herzegovina" },
  { id: 72, globe_name: "Botswana", api_name: "Botswana" },
  { id: 76, globe_name: "Brazil", api_name: "Brazil" },
  { id: 96, globe_name: "Brunei Darussalam", api_name: "Brunei Darussalam" },
  { id: 100, globe_name: "Bulgaria", api_name: "Bulgaria" },
  { id: 854, globe_name: "Burkina Faso", api_name: "Burkina Faso" },
  { id: 108, globe_name: "Burundi", api_name: "Burundi" },
  { id: 116, globe_name: "Cambodia", api_name: "Cambodia" },
  { id: 120, globe_name: "Cameroon", api_name: "Cameroon" },
  { id: 124, globe_name: "Canada", api_name: "Canada" },
  { id: 140, globe_name: "Central African Republic", api_name: null },
  { id: 148, globe_name: "Chad", api_name: "Chad" },
  { id: 152, globe_name: "Chile", api_name: "Chile" },
  { id: 156, globe_name: "China", api_name: "China" },
  { id: 170, globe_name: "Colombia", api_name: "Colombia" },
  { id: 178, globe_name: "Congo", api_name: "Congo" },
  { id: 180, globe_name: "Congo, the Democratic Republic of the", api_name: "Congo" },
  { id: 188, globe_name: "Costa Rica", api_name: "Costa Rica" },
  { id: 384, globe_name: "Cote d'Ivoire", api_name: "Cote-d-Ivoire" },
  { id: 191, globe_name: "Croatia", api_name: "Croatia" },
  { id: 192, globe_name: "Cuba", api_name: "Cuba" },
  { id: 196, globe_name: "Cyprus", api_name: "Cyprus" },
  { id: 203, globe_name: "Czech Republic", api_name: "Czech Republic" },
  { id: 208, globe_name: "Denmark", api_name: "Denmark" },
  { id: 262, globe_name: "Djibouti", api_name: "Djibouti" },
  { id: 214, globe_name: "Dominican Republic", api_name: "Dominican Republic" },
  { id: 218, globe_name: "Ecuador", api_name: "Ecuador" },
  { id: 818, globe_name: "Egypt", api_name: "Arab Rep of Egypt" },
  { id: 222, globe_name: "El Salvador", api_name: "El Salvador" },
  { id: 226, globe_name: "Equatorial Guinea", api_name: "Equatorial Guinea" },
  { id: 232, globe_name: "Eritrea", api_name: "Eritrea" },
  { id: 233, globe_name: "Estonia", api_name: "Estonia" },
  { id: 231, globe_name: "Ethiopia", api_name: "Ethiopia" },
  { id: 238, globe_name: "Falkland Islands (Malvinas)", api_name: null },
  { id: 242, globe_name: "Fiji", api_name: "Fiji" },
  { id: 246, globe_name: "Finland", api_name: "Finland" },
  { id: 250, globe_name: "France", api_name: "France" },
  { id: 260, globe_name: "French Southern Territories", api_name: null },
  { id: 266, globe_name: "Gabon", api_name: "Gabon" },
  { id: 270, globe_name: "Gambia", api_name: "The Gambia" },
  { id: 268, globe_name: "Georgia", api_name: "Georgia" },
  { id: 276, globe_name: "Germany", api_name: "Germany" },
  { id: 288, globe_name: "Ghana", api_name: "Ghana" },
  { id: 300, globe_name: "Greece", api_name: "Greece" },
  { id: 304, globe_name: "Greenland", api_name: null },
  { id: 320, globe_name: "Guatemala", api_name: "Guatemala" },
  { id: 324, globe_name: "Guinea", api_name: "Guinea" },
  { id: 624, globe_name: "Guinea-Bissau", api_name: "Guinea-Bissau" },
  { id: 328, globe_name: "Guyana", api_name: "Guyana" },
  { id: 332, globe_name: "Haiti", api_name: "Haiti" },
  { id: 340, globe_name: "Honduras", api_name: "Honduras" },
  { id: 348, globe_name: "Hungary", api_name: "Hungary" },
  { id: 352, globe_name: "Iceland", api_name: "Iceland" },
  { id: 356, globe_name: "India", api_name: "India" },
  { id: 360, globe_name: "Indonesia", api_name: "Indonesia" },
  { id: 364, globe_name: "Iran, Islamic Republic of", api_name: "Islamic Republic of Iran" },
  { id: 368, globe_name: "Iraq", api_name: "Iraq" },
  { id: 372, globe_name: "Ireland", api_name: "Ireland" },
  { id: 376, globe_name: "Israel", api_name: "Israel" },
  { id: 380, globe_name: "Italy", api_name: "Italy" },
  { id: 388, globe_name: "Jamaica", api_name: "Jamaica" },
  { id: 392, globe_name: "Japan", api_name: "Japan" },
  { id: 400, globe_name: "Jordan", api_name: "Jordan" },
  { id: 398, globe_name: "Kazakhstan", api_name: "Kazakhstan" },
  { id: 404, globe_name: "Kenya", api_name: "Kenya" },
  { id: 408, globe_name: "Korea, Democratic People's Republic of", api_name: "Dem Peoples Rep of Korea" },
  { id: 410, globe_name: "Korea, Republic of", api_name: "Rep of Korea" },
  { id: 414, globe_name: "Kuwait", api_name: "Kuwait" },
  { id: 417, globe_name: "Kyrgyzstan", api_name: "Kyrgyz Republic" },
  { id: 418, globe_name: "Lao People's Democratic Republic", api_name: "Lao PDR" },
  { id: 428, globe_name: "Latvia", api_name: "Latvia" },
  { id: 422, globe_name: "Lebanon", api_name: "Lebanon" },
  { id: 426, globe_name: "Lesotho", api_name: "Lesotho" },
  { id: 430, globe_name: "Liberia", api_name: "Liberia" },
  { id: 434, globe_name: "Libya", api_name: "Libya" },
  { id: 440, globe_name: "Lithuania", api_name: "Lithuania" },
  { id: 442, globe_name: "Luxembourg", api_name: "Luxembourg" },
  { id: 807, globe_name: "Macedonia, the former Yugoslav Republic of", api_name: "FYR Macedonia" },
  { id: 450, globe_name: "Madagascar", api_name: "Madagascar" },
  { id: 454, globe_name: "Malawi", api_name: "Malawi" },
  { id: 458, globe_name: "Malaysia", api_name: "Malaysia" },
  { id: 466, globe_name: "Mali", api_name: "Mali" },
  { id: 478, globe_name: "Mauritania", api_name: "Mauritania" },
  { id: 484, globe_name: "Mexico", api_name: "Mexico" },
  { id: 498, globe_name: "Moldova, Republic of", api_name: "Moldova" },
  { id: 496, globe_name: "Mongolia", api_name: "Mongolia" },
  { id: 499, globe_name: "Montenegro", api_name: "Montenegro" },
  { id: 504, globe_name: "Morocco", api_name: "Morocco" },
  { id: 508, globe_name: "Mozambique", api_name: "Mozambique" },
  { id: 104, globe_name: "Myanmar", api_name: "Myanmar" },
  { id: 516, globe_name: "Namibia", api_name: "Namibia" },
  { id: 524, globe_name: "Nepal", api_name: "Nepal" },
  { id: 528, globe_name: "Netherlands", api_name: "The Netherlands" },
  { id: 540, globe_name: "New Caledonia", api_name: "New Caledonia" },
  { id: 554, globe_name: "New Zealand", api_name: "New Zealand" },
  { id: 558, globe_name: "Nicaragua", api_name: "Nicaragua" },
  { id: 562, globe_name: "Niger", api_name: "Niger" },
  { id: 566, globe_name: "Nigeria", api_name: "Nigeria" },
  { id: 578, globe_name: "Norway", api_name: "Norway" },
  { id: 512, globe_name: "Oman", api_name: "Oman" },
  { id: 586, globe_name: "Pakistan", api_name: "Pakistan" },
  { id: 275, globe_name: "Palestinian Territory, Occupied", api_name: null },
  { id: 591, globe_name: "Panama", api_name: "Panama" },
  { id: 598, globe_name: "Papua New Guinea", api_name: "Papua New Guinea" },
  { id: 600, globe_name: "Paraguay", api_name: "Paraguay" },
  { id: 604, globe_name: "Peru", api_name: "Peru" },
  { id: 608, globe_name: "Philippines", api_name: "Phillipines" },
  { id: 616, globe_name: "Poland", api_name: "Poland" },
  { id: 620, globe_name: "Portugal", api_name: "Portugal" },
  { id: 630, globe_name: "Puerto Rico", api_name: "Puerto Rico" },
  { id: 634, globe_name: "Qatar", api_name: "Qatar" },
  { id: 642, globe_name: "Romania", api_name: "Romania" },
  { id: 643, globe_name: "Russian Federation", api_name: "Russian Federation" },
  { id: 646, globe_name: "Rwanda", api_name: "Rwanda" },
  { id: 682, globe_name: "Saudi Arabia", api_name: "Saudi Arabia" },
  { id: 686, globe_name: "Senegal", api_name: "Senegal" },
  { id: 688, globe_name: "Serbia", api_name: "Serbia" },
  { id: 694, globe_name: "Sierra Leone", api_name: "Sierra Leone" },
  { id: 703, globe_name: "Slovakia", api_name: "Slovak Republic" },
  { id: 705, globe_name: "Slovenia", api_name: "Slovenia" },
  { id: 90, globe_name: "Solomon Islands", api_name: "Solomon Islands" },
  { id: 706, globe_name: "Somalia", api_name: "Somalia" },
  { id: 710, globe_name: "South Africa", api_name: "South Africa" },
  { id: 728, globe_name: "South Sudan", api_name: "South Sudan" },
  { id: 724, globe_name: "Spain", api_name: "Spain" },
  { id: 144, globe_name: "Sri Lanka", api_name: "Sri Lanka" },
  { id: 729, globe_name: "Sudan", api_name: "Sudan" },
  { id: 740, globe_name: "Suriname", api_name: "Suriname" },
  { id: 748, globe_name: "Swaziland", api_name: "Swaziland" },
  { id: 752, globe_name: "Sweden", api_name: "Sweden" },
  { id: 756, globe_name: "Switzerland", api_name: "Switzerland" },
  { id: 760, globe_name: "Syrian Arab Republic", api_name: "Syrian Arab Rep" },
  { id: 158, globe_name: "Taiwan, Province of China", api_name: null },
  { id: 762, globe_name: "Tajikistan", api_name: "Tajikistan" },
  { id: 834, globe_name: "Tanzania, United Republic of", api_name: "Tanzania" },
  { id: 764, globe_name: "Thailand", api_name: "Thailand" },
  { id: 626, globe_name: "Timor-Leste", api_name: "Timor-Leste" },
  { id: 768, globe_name: "Togo", api_name: "Togo" },
  { id: 780, globe_name: "Trinidad and Tobago", api_name: "Trinidad and Tobago" },
  { id: 788, globe_name: "Tunisia", api_name: "Tunisia" },
  { id: 792, globe_name: "Turkey", api_name: "Turkey" },
  { id: 795, globe_name: "Turkmenistan", api_name: "Turkmenistan" },
  { id: 800, globe_name: "Uganda", api_name: "Uganda" },
  { id: 804, globe_name: "Ukraine", api_name: "Ukraine" },
  { id: 784, globe_name: "United Arab Emirates", api_name: "United Arab Emirates" },
  { id: 826, globe_name: "United Kingdom", api_name: "United Kingdom" },
  { id: 840, globe_name: "United States", api_name: "United States" },
  { id: 858, globe_name: "Uruguay", api_name: "Uruguay" },
  { id: 860, globe_name: "Uzbekistan", api_name: "Uzbekistan" },
  { id: 548, globe_name: "Vanuatu", api_name: "Vanuatu" },
  { id: 862, globe_name: "Venezuela, Bolivarian Republic of", api_name: "RB-de-Venezuela" },
  { id: 704, globe_name: "Viet Nam", api_name: "Vietnam" },
  { id: 732, globe_name: "Western Sahara", api_name: "Western Sahara" },
  { id: 887, globe_name: "Yemen", api_name: "Rep of Yemen" },
  { id: 894, globe_name: "Zambia", api_name: "Zambia" },
  { id: 716, globe_name: "Zimbabwe", api_name: "Zimbabwe" }
]

export default function (name) {
  return countries.find(country => country.globe_name == name).api_name
} 